[package]
name = "wad-rs"
version = "0.1.1"
edition = "2024"
authors = ["Mathias LÃ¼er<m.lueer80@gmail.com>"]
description = "A Rust library for indexing WAD files and converting Lumps to more usable formats."

[dependencies]
fm-synth = { version = "0.1.0", path = "fm-synth" }
rodio = "0.21.1"
rustysynth = "1.3.6"

[dev-dependencies]
criterion = "0.8.1"

[[bin]]
name = "profile"
path = "src/bin/profile.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[[bench]]
name = "benchmarks"
harness = false
path = "benches/benchmarks.rs"
